### ISSUE TITLE
CLIApplication doesn't call all delegate methods

### ISSUE THREAD

**Issue by umjames** [umjames/CLIKit#2]
Make sure all CLIApplicationDelegate methods are called during a run of the CLIApplication object.

**Comment by levigroker** [comment]
Hi there, I think I've encountered (one) manifestation of this... `application:isReadyToBeginExecutingWithRemainingArguments:` does not get called if there are no non-option arguments passed in via the command line. i.e. if I just pass -options the delegate method never gets fired and my app does nothing.
